"""Criar tabelas iniciais

Revision ID: 8095ecceab76
Revises: 
Create Date: 2024-10-14 11:19:06.421618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8095ecceab76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entry', schema=None) as batch_op:
        batch_op.alter_column('aceite_termos',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entry', schema=None) as batch_op:
        batch_op.alter_column('aceite_termos',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
