"""Adiciona coluna resposta_sim_nao à tabela FormEntry

Revision ID: cae35e58fd13
Revises: 8095ecceab76
Create Date: 2024-10-21 15:03:24.126001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae35e58fd13'
down_revision = '8095ecceab76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional_check', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entry', schema=None) as batch_op:
        batch_op.drop_column('regional_check')

    # ### end Alembic commands ###
