"""Adiciona coluna resposta_sim_nao à tabela FormEntry

Revision ID: f93b6080c0b3
Revises: cae35e58fd13
Create Date: 2024-10-21 15:11:51.748524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93b6080c0b3'
down_revision = 'cae35e58fd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional_check', sa.String(length=3), nullable=True))

    with op.batch_alter_table('form_entry', schema=None) as batch_op:
        batch_op.drop_column('regional_check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional_check', sa.VARCHAR(length=3), autoincrement=False, nullable=True))

    with op.batch_alter_table('avaliacao_entry', schema=None) as batch_op:
        batch_op.drop_column('regional_check')

    # ### end Alembic commands ###
